const ExcelJS = require('exceljs');
const path = require('path');

// Raw tasks from generate_workbook.js
const tasksRaw = [
  // INFRASTRUCTURE (9 tasks)
  [
    'TASK-INF-001',
    'Infrastructure',
    'Repository verification',
    'Adithyan N + Muhammad Sanish',
    'High',
    'Sprint 0',
    'None',
    'Verified local Git repository and node workspace structures',
    'Yes',
    'No',
    'Check configuration files integrity',
  ],
  [
    'TASK-INF-002',
    'Infrastructure',
    'Git workflow setup',
    'Adithyan N',
    'High',
    'Sprint 0',
    'None',
    'Repository branching model and commit rules defined',
    'No',
    'No',
    'Main/develop/feature branching rules',
  ],
  [
    'TASK-INF-003',
    'Infrastructure',
    'Branch setup',
    'Adithyan N',
    'High',
    'Sprint 0',
    'TASK-INF-002',
    'Feature branches initialized on GitHub',
    'No',
    'No',
    'Initial pull request guidelines set',
  ],
  [
    'TASK-INF-004',
    'Infrastructure',
    'MongoDB Atlas setup',
    'Adithyan N',
    'Critical',
    'Sprint 0',
    'None',
    'Live MongoDB Atlas sandbox cluster initialized with access controls',
    'Yes',
    'Yes',
    'IP whitelist rules configured',
  ],
  [
    'TASK-INF-005',
    'Infrastructure',
    'Environment variables',
    'Muhammad Sanish',
    'High',
    'Sprint 0',
    'None',
    '.env.example templates configuration sheets',
    'Yes',
    'Yes',
    'No secrets checked in',
  ],
  [
    'TASK-INF-006',
    'Infrastructure',
    'ESLint',
    'Adithyan N',
    'Medium',
    'Sprint 0',
    'None',
    'ESLint standards rules deployed to repository root',
    'Yes',
    'No',
    'Static code styling checks active',
  ],
  [
    'TASK-INF-007',
    'Infrastructure',
    'Prettier',
    'Adithyan N',
    'Medium',
    'Sprint 0',
    'None',
    'Prettier formats scripts configured',
    'Yes',
    'No',
    'Auto format on save verified',
  ],
  [
    'TASK-INF-008',
    'Infrastructure',
    'Logging infrastructure',
    'Muhammad Sanish',
    'Medium',
    'Day 1',
    'TASK-INF-005',
    'Winston/Morgan logger system with data masking logic',
    'Yes',
    'Yes',
    'PII credentials redact scripts applied',
  ],
  [
    'TASK-INF-009',
    'Infrastructure',
    'Deployment preparation',
    'Adithyan N + Muhammad Sanish',
    'Medium',
    'Day 7',
    'None',
    'Render/Vercel MVP launch readiness report',
    'Yes',
    'Yes',
    'Production CORS policies configured',
  ],

  // DATABASE (16 tasks)
  [
    'TASK-DB-001',
    'Database',
    'User schema',
    'Fathima Hana',
    'Critical',
    'Day 1',
    'TASK-INF-004',
    'Mongoose schema for users collection',
    'Yes',
    'Yes',
    'Support: Adithyan N. Unique key bounds active',
  ],
  [
    'TASK-DB-002',
    'Database',
    'Role schema',
    'Fathima Hana',
    'High',
    'Day 1',
    'TASK-DB-001',
    'Roles allocation definition mapping schemas',
    'Yes',
    'Yes',
    'Support: Adithyan N. Predefined roles seeded',
  ],
  [
    'TASK-DB-003',
    'Database',
    'Permission schema',
    'Fathima Hana',
    'High',
    'Day 1',
    'TASK-DB-002',
    'Permissions collection schemas definition mapping routes',
    'Yes',
    'Yes',
    'Support: Adithyan N. RBAC maps',
  ],
  [
    'TASK-DB-004',
    'Database',
    'Department schema',
    'Fathima Hana',
    'Medium',
    'Day 1',
    'TASK-DB-001',
    'Department schemas mapping employees',
    'Yes',
    'No',
    'Support: Adithyan N. Collection indices',
  ],
  [
    'TASK-DB-005',
    'Database',
    'Complaint schema',
    'Fathima Hana',
    'Critical',
    'Day 2',
    'TASK-DB-001',
    'Complaints database models with status trackers',
    'Yes',
    'Yes',
    'Support: Adithyan N. Handles attachments path strings',
  ],
  [
    'TASK-DB-006',
    'Database',
    'Complaint assignment schema',
    'Fathima Hana',
    'High',
    'Day 2',
    'TASK-DB-005',
    'Assignments tracking schemas mapping assignees and times',
    'Yes',
    'No',
    'Support: Adithyan N. References user and complaint',
  ],
  [
    'TASK-DB-007',
    'Database',
    'File tracking schema',
    'Fathima Hana',
    'Medium',
    'Day 3',
    'TASK-DB-005',
    'File_tracking and progress steps schemas mapping',
    'Yes',
    'No',
    'Support: Adithyan N. Tracks history steps',
  ],
  [
    'TASK-DB-008',
    'Database',
    'Feedback schema',
    'Fathima Hana',
    'Medium',
    'Day 3',
    'TASK-DB-005',
    'Customer feedback rating collection schema setup',
    'Yes',
    'No',
    'Support: Adithyan N. Constraints bounds checks',
  ],
  [
    'TASK-DB-009',
    'Database',
    'Attendance schema',
    'Fathima Hana',
    'High',
    'Day 4',
    'TASK-DB-001',
    'Staff attendance punch records logs schema mapping',
    'Yes',
    'Yes',
    'Support: Adithyan N. Biometric template matches parameters',
  ],
  [
    'TASK-DB-010',
    'Database',
    'Notification schema',
    'Fathima Hana',
    'Medium',
    'Day 5',
    'TASK-DB-001',
    'System alerts database logging schemas',
    'Yes',
    'No',
    'Support: Adithyan N. Unread indicators',
  ],
  [
    'TASK-DB-011',
    'Database',
    'Audit log schema',
    'Fathima Hana',
    'High',
    'Day 5',
    'TASK-DB-001',
    'Append-only transactional events audit logging schema',
    'Yes',
    'Yes',
    'Support: Adithyan N. Strict immutability controls',
  ],
  [
    'TASK-DB-012',
    'Database',
    'Chatbot session schema',
    'Fathima Hana',
    'Medium',
    'Day 4',
    'TASK-DB-001',
    'Chat conversation logs databases tracking structures',
    'Yes',
    'No',
    'Support: Adithyan N. Session TTL setup',
  ],
  [
    'TASK-DB-013',
    'Database',
    'Indexes',
    'Fathima Hana',
    'High',
    'Day 1',
    'TASK-DB-001',
    'Unique indices mapping user emails and tracking file ID keys',
    'Yes',
    'No',
    'Support: Adithyan N. Index strategies verified',
  ],
  [
    'TASK-DB-014',
    'Database',
    'Relationships',
    'Fathima Hana',
    'Medium',
    'Day 1',
    'TASK-DB-002',
    'Foreign object reference bounds configuration in schemas',
    'Yes',
    'No',
    'Support: Adithyan N. Strict Mongoose validations',
  ],
  [
    'TASK-DB-015',
    'Database',
    'Validation rules',
    'Fathima Hana',
    'High',
    'Day 1',
    'TASK-DB-001',
    'Mongoose validators evaluating text formats and coordinate bounds',
    'Yes',
    'Yes',
    'Support: Adithyan N. Input sanity checker',
  ],
  [
    'TASK-DB-016',
    'Database',
    'Query optimization',
    'Fathima Hana',
    'Medium',
    'Day 6',
    'TASK-DB-013',
    'Explain query plans validation analysis records',
    'Yes',
    'No',
    'Support: Adithyan N. Optimizing pipeline matches',
  ],

  // BACKEND (20 tasks)
  [
    'TASK-BE-001',
    'Backend',
    'Express setup',
    'Muhammad Sanish',
    'Critical',
    'Day 1',
    'TASK-INF-005',
    'Express server layout initialized with Helmet and CORS settings',
    'Yes',
    'Yes',
    'Security middleware active',
  ],
  [
    'TASK-BE-002',
    'Backend',
    'MongoDB connection',
    'Muhammad Sanish',
    'Critical',
    'Day 1',
    'TASK-INF-004',
    'Mongoose database connector with auto-retry logics',
    'Yes',
    'No',
    'Connection pool set to 10 connections max',
  ],
  [
    'TASK-BE-003',
    'Backend',
    'Environment configuration',
    'Muhammad Sanish',
    'High',
    'Day 1',
    'TASK-INF-005',
    'Dotenv loader checking and validating essential keys',
    'Yes',
    'Yes',
    'Throws startup error on missing keys',
  ],
  [
    'TASK-BE-004',
    'Backend',
    'Authentication APIs',
    'Muhammad Sanish',
    'Critical',
    'Day 2',
    'TASK-BE-001',
    'Login and signup backend API router endpoints',
    'Yes',
    'Yes',
    'Bcrypt salt rounds configured',
  ],
  [
    'TASK-BE-005',
    'Backend',
    'JWT implementation',
    'Muhammad Sanish',
    'Critical',
    'Day 2',
    'TASK-BE-004',
    'Access token issuance logic mapped to JWT key payload',
    'Yes',
    'Yes',
    'Token expires in 15 mins',
  ],
  [
    'TASK-BE-006',
    'Backend',
    'Refresh token API',
    'Muhammad Sanish',
    'High',
    'Day 2',
    'TASK-BE-005',
    'Rotating refresh token endpoints validations',
    'Yes',
    'Yes',
    'Secure cookie transport tags configuration',
  ],
  [
    'TASK-BE-007',
    'Backend',
    'Logout API',
    'Muhammad Sanish',
    'Medium',
    'Day 2',
    'TASK-BE-005',
    'Token cleanup and session revocation middleware endpoints',
    'Yes',
    'No',
    'Revokes active refresh session',
  ],
  [
    'TASK-BE-008',
    'Backend',
    'RBAC middleware',
    'Muhammad Sanish',
    'Critical',
    'Day 1',
    'TASK-BE-005',
    'Gated endpoint middleware evaluating token permissions',
    'Yes',
    'Yes',
    'Role sets validation checks',
  ],
  [
    'TASK-BE-009',
    'Backend',
    'Audit logging',
    'Muhammad Sanish',
    'High',
    'Day 5',
    'TASK-BE-002',
    'Transactional logging controller mapping security events',
    'Yes',
    'Yes',
    'Writes directly to audit_logs collection',
  ],
  [
    'TASK-BE-010',
    'Backend',
    'Error middleware',
    'Muhammad Sanish',
    'Medium',
    'Day 1',
    'TASK-BE-001',
    'Centralized Express error handlers parsing exceptions',
    'Yes',
    'No',
    'Redacts stack traces in production environment',
  ],
  [
    'TASK-BE-011',
    'Backend',
    'Validation middleware',
    'Muhammad Sanish',
    'High',
    'Day 1',
    'TASK-BE-001',
    'Body/params query schemas validator middlewares',
    'Yes',
    'Yes',
    'Strips unauthorized fields',
  ],
  [
    'TASK-BE-012',
    'Backend',
    'Complaint APIs',
    'Muhammad Sanish',
    'High',
    'Day 2',
    'TASK-BE-008',
    'Create, update, assign, and query complaints APIs',
    'Yes',
    'Yes',
    'Resource ownership validations active',
  ],
  [
    'TASK-BE-013',
    'Backend',
    'File Tracking APIs',
    'Muhammad Sanish',
    'Medium',
    'Day 3',
    'TASK-BE-008',
    'Public tracking progress endpoint lookup',
    'Yes',
    'Yes',
    'Suppresses internal notes and logs on public view',
  ],
  [
    'TASK-BE-014',
    'Backend',
    'Feedback APIs',
    'Muhammad Sanish',
    'Medium',
    'Day 3',
    'TASK-BE-012',
    'Complaint feedback rating submission and ticket locking controller',
    'Yes',
    'No',
    'Locks complaints database records on completion',
  ],
  [
    'TASK-BE-015',
    'Backend',
    'Attendance APIs',
    'Muhammad Sanish',
    'High',
    'Day 4',
    'TASK-BE-008',
    'Attendance punch registers and consent flags lookup endpoints',
    'Yes',
    'Yes',
    'Validates consent status before scan logic',
  ],
  [
    'TASK-BE-016',
    'Backend',
    'Admin APIs',
    'Muhammad Sanish',
    'High',
    'Day 5',
    'TASK-BE-008',
    'System configurations and user details updates controls APIs',
    'Yes',
    'Yes',
    'Enforces strict Admin role checks',
  ],
  [
    'TASK-BE-017',
    'Backend',
    'Notification APIs',
    'Muhammad Sanish',
    'Medium',
    'Day 5',
    'TASK-BE-001',
    'Trigger notification records and dispatch to DB logs',
    'Yes',
    'No',
    'System alert logs generation',
  ],
  [
    'TASK-BE-018',
    'Backend',
    'Rate limiting',
    'Muhammad Sanish',
    'High',
    'Day 1',
    'TASK-BE-001',
    'Rate-limiter setup restricting requests per IP window',
    'Yes',
    'Yes',
    'Prevents brute force attempts',
  ],
  [
    'TASK-BE-019',
    'Backend',
    'Health check API',
    'Muhammad Sanish',
    'Low',
    'Day 1',
    'TASK-BE-001',
    'Diagnostics route returning system status',
    'Yes',
    'No',
    'Returns DB status and memory limits details',
  ],
  [
    'TASK-BE-020',
    'Backend',
    'API documentation',
    'Muhammad Sanish',
    'Medium',
    'Day 5',
    'TASK-BE-001',
    'Swagger/OpenAPI backend routing contracts layout',
    'Yes',
    'No',
    'Complete document of schema request bodies',
  ],

  // FRONTEND (24 tasks)
  [
    'TASK-FE-001',
    'Frontend',
    'React project setup',
    'Adithyan N',
    'High',
    'Day 1',
    'None',
    'Vite React scaffold template created',
    'Yes',
    'No',
    'Project workspace initialized',
  ],
  [
    'TASK-FE-002',
    'Frontend',
    'Tailwind setup',
    'Adithyan N',
    'High',
    'Day 1',
    'TASK-FE-001',
    'Tailwind utility framework config initialized',
    'Yes',
    'No',
    'Custom theme color palettes mapped',
  ],
  [
    'TASK-FE-003',
    'Frontend',
    'Folder structure',
    'Adithyan N',
    'Medium',
    'Day 1',
    'TASK-FE-001',
    'Standard client pages/components directory structured',
    'No',
    'No',
    'Standard clean coding layout',
  ],
  [
    'TASK-FE-004',
    'Frontend',
    'Global layout',
    'Adithyan N',
    'High',
    'Day 1',
    'TASK-FE-003',
    'Responsive sidebars and navigation headers layouts',
    'Yes',
    'No',
    'Mobile responsive shell layout',
  ],
  [
    'TASK-FE-005',
    'Frontend',
    'Routing',
    'Adithyan N',
    'High',
    'Day 1',
    'TASK-FE-001',
    'React Router paths configuration mapping',
    'Yes',
    'No',
    'URL router structure finalized',
  ],
  [
    'TASK-FE-006',
    'Frontend',
    'Protected routes',
    'Adithyan N',
    'High',
    'Day 1',
    'TASK-FE-005',
    'Route wrapper gating views based on user login token',
    'Yes',
    'Yes',
    'Redirects guest to login page',
  ],
  [
    'TASK-FE-007',
    'Frontend',
    'Axios client',
    'Adithyan N',
    'High',
    'Day 1',
    'None',
    'Custom Axios client class initialized',
    'Yes',
    'No',
    'Base configuration templates',
  ],
  [
    'TASK-FE-008',
    'Frontend',
    'API interceptors',
    'Adithyan N',
    'High',
    'Day 1',
    'TASK-FE-007',
    'JWT token injection request/response interceptors',
    'Yes',
    'Yes',
    'Auto attaches auth tokens to headers',
  ],
  [
    'TASK-FE-009',
    'Frontend',
    'Authentication pages',
    'Adithyan N',
    'High',
    'Day 2',
    'TASK-FE-006',
    'Responsive Login and registration forms UI layouts',
    'Yes',
    'Yes',
    'Client side input validation rules active',
  ],
  [
    'TASK-FE-010',
    'Frontend',
    'Citizen Dashboard',
    'Adithyan N',
    'High',
    'Day 2',
    'TASK-FE-006',
    'Grievance list overview panel and stats widgets UI',
    'Yes',
    'No',
    'Overview dashboard for citizen portals',
  ],
  [
    'TASK-FE-011',
    'Frontend',
    'Complaint Management UI',
    'Adithyan N',
    'High',
    'Day 2',
    'TASK-FE-010',
    'Complaint intake form components with file attachment uploaders',
    'Yes',
    'Yes',
    'File type constraints validated',
  ],
  [
    'TASK-FE-012',
    'Frontend',
    'File Tracking UI',
    'Adithyan N',
    'Medium',
    'Day 3',
    'TASK-FE-008',
    'Public timeline tracking status lookup bar',
    'Yes',
    'No',
    'Visual timeline progress trackers',
  ],
  [
    'TASK-FE-013',
    'Frontend',
    'Feedback UI',
    'Adithyan N',
    'Medium',
    'Day 3',
    'TASK-FE-011',
    'Satisfaction ratings component locking solved complaints',
    'Yes',
    'No',
    '1-to-5 star feedback rating',
  ],
  [
    'TASK-FE-014',
    'Frontend',
    'Staff Dashboard UI',
    'Adithyan N',
    'High',
    'Day 4',
    'TASK-FE-006',
    'Kanban view and ticket updates action buttons',
    'Yes',
    'Yes',
    'Workspace console for employees',
  ],
  [
    'TASK-FE-015',
    'Frontend',
    'Attendance UI',
    'Adithyan N',
    'High',
    'Day 4',
    'TASK-FE-014',
    'Webcam consent prompt and face scan punch window',
    'Yes',
    'Yes',
    'Liveness prompt overlay layout',
  ],
  [
    'TASK-FE-016',
    'Frontend',
    'Chatbot UI',
    'Adithyan N',
    'Medium',
    'Day 4',
    'TASK-FE-008',
    'Conversational chat container overlays widget UI',
    'Yes',
    'No',
    'Gemini assistant layout UI',
  ],
  [
    'TASK-FE-017',
    'Frontend',
    'Admin Dashboard UI',
    'Adithyan N',
    'High',
    'Day 5',
    'TASK-FE-006',
    'User lists management, SLAs settings, and parameters tables',
    'Yes',
    'Yes',
    'SLA thresholds controller views',
  ],
  [
    'TASK-FE-018',
    'Frontend',
    'Notifications UI',
    'Adithyan N',
    'Medium',
    'Day 5',
    'TASK-FE-008',
    'Alert toasts lists dropdown console UI',
    'Yes',
    'No',
    'Toast popups integrations',
  ],
  [
    'TASK-FE-019',
    'Frontend',
    'Reusable Components',
    'Adithyan N',
    'Medium',
    'Day 1',
    'TASK-FE-002',
    'Standard buttons, forms input fields, modal dialogs library',
    'Yes',
    'No',
    'Common component assets',
  ],
  [
    'TASK-FE-020',
    'Frontend',
    'Responsive fixes',
    'Adithyan N',
    'Medium',
    'Day 6',
    'TASK-FE-004',
    'Media queries tweaks on mobile viewports',
    'Yes',
    'No',
    'Fluid grids testing',
  ],
  [
    'TASK-FE-021',
    'Frontend',
    'Frontend API integration',
    'Adithyan N',
    'High',
    'Day 5',
    'TASK-FE-008',
    'Connect React layouts to Express server routes API endpoints',
    'Yes',
    'Yes',
    'Integration mapping verified',
  ],
  [
    'TASK-FE-022',
    'Frontend',
    'Error boundaries',
    'Adithyan N',
    'Low',
    'Day 1',
    'TASK-FE-001',
    'React fallback boundaries catching rendering errors',
    'Yes',
    'No',
    'No stack details shown in production UI',
  ],
  [
    'TASK-FE-023',
    'Frontend',
    'Loading components',
    'Adithyan N',
    'Low',
    'Day 1',
    'TASK-FE-001',
    'Standardized skeleton loader elements',
    'Yes',
    'No',
    'Visual placeholders setup',
  ],
  [
    'TASK-FE-024',
    'Frontend',
    'Final UI testing',
    'Adithyan N',
    'High',
    'Day 7',
    'TASK-FE-021',
    'E2E visual verification and usability test runs report',
    'Yes',
    'No',
    'UX verification pass signoff',
  ],

  // AI (9 tasks)
  [
    'TASK-AI-001',
    'AI',
    'Gemini integration',
    'Muhammed Sadik KT',
    'High',
    'Day 4',
    'None',
    'Gemini API client connection script with prompt instructions',
    'Yes',
    'Yes',
    'RAG context grounding middleware',
  ],
  [
    'TASK-AI-002',
    'AI',
    'Prompt engineering',
    'Muhammed Sadik KT',
    'Medium',
    'Day 4',
    'TASK-AI-001',
    'System instructions locking AI answers within municipality docs',
    'Yes',
    'No',
    'Strict grounding bounds',
  ],
  [
    'TASK-AI-003',
    'AI',
    'Chatbot API',
    'Muhammed Sadik KT',
    'High',
    'Day 4',
    'TASK-AI-001',
    'Express server routing chat session controller endpoints',
    'Yes',
    'Yes',
    'Logs sessions to chatbot DB logs',
  ],
  [
    'TASK-AI-004',
    'AI',
    'OCR service',
    'Muhammed Sadik KT',
    'Medium',
    'Day 5',
    'None',
    'PDF/image character recognition text extractor service',
    'Yes',
    'Yes',
    'Sandbox process execution setup',
  ],
  [
    'TASK-AI-005',
    'AI',
    'OCR validation',
    'Muhammed Sadik KT',
    'Medium',
    'Day 5',
    'TASK-AI-004',
    'Extracted texts checks validating document details matching',
    'Yes',
    'Yes',
    'Verify metadata matching limits',
  ],
  [
    'TASK-AI-006',
    'AI',
    'Face recognition core',
    'Muhammed Sadik KT',
    'Critical',
    'Day 4',
    'None',
    'Python comparison scripts checking face points similarity',
    'Yes',
    'Yes',
    'Volatile memory calculations',
  ],
  [
    'TASK-AI-007',
    'AI',
    'Attendance recognition service',
    'Muhammed Sadik KT',
    'High',
    'Day 4',
    'TASK-AI-006',
    'Biometrics validation punch connector API',
    'Yes',
    'Yes',
    'Liveness score validation criteria check',
  ],
  [
    'TASK-AI-008',
    'AI',
    'AI testing',
    'Muhammed Sadik KT',
    'Medium',
    'Day 5',
    'TASK-AI-007',
    'Biometrics matching FAR/FRR testing checklist documentation',
    'Yes',
    'Yes',
    'Checks accuracy scales',
  ],
  [
    'TASK-AI-009',
    'AI',
    'Response optimization',
    'Muhammed Sadik KT',
    'Medium',
    'Day 5',
    'TASK-AI-002',
    'Fine-tuned prompt parameters shortening delay intervals',
    'Yes',
    'No',
    'RAG search optimizations',
  ],

  // FACE RECOGNITION (9 tasks)
  [
    'TASK-FR-001',
    'Face Recognition',
    'Dataset Collection',
    'Fadi Ahmed',
    'Medium',
    'Day 4',
    'None',
    'Standardized baseline test faces calibration datasets',
    'Yes',
    'Yes',
    'No images checked in repository',
  ],
  [
    'TASK-FR-002',
    'Face Recognition',
    'Prototype Refinement',
    'Fadi Ahmed',
    'High',
    'Day 4',
    'TASK-AI-006',
    'Optimized points extraction models',
    'Yes',
    'Yes',
    'Anti-spoofing tests calibration',
  ],
  [
    'TASK-FR-003',
    'Face Recognition',
    'Camera Integration Testing',
    'Fadi Ahmed',
    'Medium',
    'Day 4',
    'None',
    'HTML5 webcam access scripts checks report',
    'Yes',
    'Yes',
    'Confirm permissions logic',
  ],
  [
    'TASK-FR-004',
    'Face Recognition',
    'Attendance Workflow Testing',
    'Fadi Ahmed',
    'High',
    'Day 5',
    'TASK-FR-003',
    'Verify biometric punch registration triggers checkin updates',
    'Yes',
    'Yes',
    'Strict consent checker gating attendance validation',
  ],
  [
    'TASK-FR-005',
    'Face Recognition',
    'Recognition Accuracy Testing',
    'Fadi Ahmed',
    'High',
    'Day 5',
    'TASK-FR-002',
    'FAR and FRR metrics check data log summary',
    'Yes',
    'Yes',
    'Audits against spoof attacks',
  ],
  [
    'TASK-FR-006',
    'Face Recognition',
    'Cross-Browser Camera Testing',
    'Fadi Ahmed',
    'Medium',
    'Day 6',
    'TASK-FR-003',
    'Camera compatibility verification checks results log',
    'Yes',
    'Yes',
    'Webcam permissions tests on Safari/Firefox/Chrome',
  ],
  [
    'TASK-FR-007',
    'Face Recognition',
    'Scanner UI Review',
    'Fadi Ahmed',
    'Medium',
    'Day 4',
    'None',
    'Webcam canvas box layout alignment reviews logs',
    'Yes',
    'No',
    'UI responsiveness check',
  ],
  [
    'TASK-FR-008',
    'Face Recognition',
    'System Integration Testing',
    'Fadi Ahmed',
    'High',
    'Day 6',
    'TASK-FR-004',
    'End to end biometrics validations verification logs',
    'Yes',
    'Yes',
    'Gating RBAC reviews verified',
  ],
  [
    'TASK-FR-009',
    'Face Recognition',
    'Camera Permission Testing',
    'Fadi Ahmed',
    'Medium',
    'Day 4',
    'TASK-FR-003',
    'Verification checklists logging permission locks and denials checks',
    'Yes',
    'Yes',
    'Checks fallback options',
  ],

  // DOCUMENTATION & QA (9 tasks)
  [
    'TASK-QA-001',
    'Documentation & QA',
    'Requirement traceability',
    'Minha Palakkathodi',
    'High',
    'Day 1',
    'None',
    'RTM spreadsheet linking requirements to components code',
    'No',
    'No',
    'Traceability index setup',
  ],
  [
    'TASK-QA-002',
    'Documentation & QA',
    'Test case creation',
    'Minha Palakkathodi',
    'High',
    'Day 2',
    'TASK-QA-001',
    'Functional test cases suite covering citizen/staff actions',
    'No',
    'No',
    'Manual check sheets ready',
  ],
  [
    'TASK-QA-003',
    'Documentation & QA',
    'UAT preparation',
    'Minha Palakkathodi',
    'High',
    'Day 5',
    'None',
    'User acceptance testing checklist layout schemas',
    'No',
    'No',
    'Acceptance checklist templates',
  ],
  [
    'TASK-QA-004',
    'Documentation & QA',
    'Documentation review',
    'Minha Palakkathodi',
    'Medium',
    'Day 7',
    'None',
    'Verification and correction checklists for all docs',
    'No',
    'No',
    'Checks repository documents integrity',
  ],
  [
    'TASK-QA-005',
    'Documentation & QA',
    'Security checklist review',
    'Minha Palakkathodi',
    'High',
    'Day 7',
    'None',
    'Security validation gates signed reports',
    'No',
    'No',
    'Checks details audits validation',
  ],
  [
    'TASK-QA-006',
    'Documentation & QA',
    'QA reports',
    'Minha Palakkathodi',
    'Medium',
    'Day 6',
    'None',
    'System QA test validation results report',
    'No',
    'No',
    'Test pass metrics logs summary',
  ],
  [
    'TASK-QA-007',
    'Documentation & QA',
    'Bug verification',
    'Minha Palakkathodi',
    'High',
    'Day 6',
    'None',
    'QA verified bug tracker status validation logs',
    'No',
    'No',
    'Verify fix statuses',
  ],
  [
    'TASK-QA-008',
    'Documentation & QA',
    'Final documentation',
    'Minha Palakkathodi',
    'High',
    'Day 7',
    'None',
    'Consolidated developer documentation package',
    'No',
    'No',
    'Complete architecture references',
  ],
  [
    'TASK-QA-009',
    'Documentation & QA',
    'Handover documentation',
    'Minha Palakkathodi',
    'High',
    'Day 7',
    'TASK-QA-008',
    'Municipality handover procedures manuals checklist',
    'No',
    'No',
    'Log logins and operational keys handover structures',
  ],
];

async function compare() {
  const workbook = new ExcelJS.Workbook();
  const filePath = path.join(__dirname, '..', 'Municipality_Project_Advanced_Kanban.xlsx');
  await workbook.xlsx.readFile(filePath);

  const dash = workbook.getWorksheet('Dashboard');
  const excelTasks = [];

  for (let r = 16; r <= 111; r++) {
    const taskId = dash.getCell(r, 1).value;
    const taskName = dash.getCell(r, 3).value;
    const assignedTo = dash.getCell(r, 4).value;
    const priority = dash.getCell(r, 5).value;
    const status = dash.getCell(r, 6).value;
    const day = dash.getCell(r, 8).value;
    const dep = dash.getCell(r, 9).value;
    const remarks = dash.getCell(r, 12).value;
    const demoCritical = dash.getCell(r, 13).value;

    excelTasks.push({
      r,
      taskId,
      taskName,
      assignedTo,
      priority,
      status,
      day,
      dep,
      remarks,
      demoCritical,
    });
  }

  console.log(`Excel task count: ${excelTasks.length}`);
  console.log(`Raw task count: ${tasksRaw.length}`);

  let diffs = 0;
  tasksRaw.forEach((raw, idx) => {
    const excel = excelTasks[idx];
    if (!excel) {
      console.log(`Missing task in Excel at index ${idx}:`, raw[0]);
      diffs++;
      return;
    }
    if (excel.taskId !== raw[0]) {
      console.log(`Task ID mismatch at row ${excel.r}: Excel=${excel.taskId}, Raw=${raw[0]}`);
      diffs++;
    }
  });

  if (diffs === 0) {
    console.log(
      'Success: All task IDs match exactly between existing Excel file and raw generator array!'
    );
  } else {
    console.log(`Found ${diffs} mismatches.`);
  }
}

compare().catch(console.error);
